---
- hosts: 172.31.4.232
  become: yes
  tasks:
  - name: I want to execute direct command
    command: hostname -f
    register: myhostname

  - name: display first task result
    debug: 
       msg: "{{myhostname}}"
       