---
- hosts: 172.31.4.232
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install webserver
    apt:
      name: apache2
      state: present 

  - name: copy file into remote servers
    copy:
      src: mystatictestfile
      dest: /home/ubuntu/mystatictestfile
  - name: download internet file
    get_url: 
       url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.87/bin/apache-tomcat-9.0.87.zip
       dest: /home/ubuntu/apache-tomcat-9.0.87.zip
       force_basic_auth: yes
  - name: copy index file into nodeside
    template:
       src: myindex.j2
       dest: /var/www/html/index.html
    notify: restartwebserver

  handlers:
  - name: restartwebserver
    service:
       name: apache2
       state: restarted