---
- hosts: 172.31.4.232
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install webserver
    apt:
      name: apache2
      state: present 

  - name: copy file into remote servers
    copy:
      src: mystatictestfile
      dest: /home/ubuntu/mystatictestfile
