---
- hosts: mywebservers 
  become: yes
  tasks:
  - name: install webserver on ansible nodes
    apt: 
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: start webserver on ansible nodes
    service: 
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family =="Debian"