---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on ansible nodes
    apt: 
      name: apache2
      state: present
  - name: start webserver on ansible nodes
    service: apache2
    state: started