---
- name: download tar file
  get_url:
     src: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
     dest: /home/sujith1/apache-tomcat-10.0.20.tar.gz
     force_basic_auth: yes

- name: extract tar file
  command: sudo tar xzvf /home/sujith1/apache-tomcat-10.0.20.tar.gz -C /opt/tomcat --strip-components=1
  creates: /opt/tomcat/LICENSE 